export const gearScoreTable: { [key: string]: { [rarity: string]: number } } = {
  primaryWeapon: {
    poor: 1,
    common: 2,
    uncommon: 27,
    rare: 36,
    epic: 54,
    legendary: 72,
    unique: 125,
  },
  twoHanded: {
    poor: 2,
    common: 4,
    uncommon: 45,
    rare: 60,
    epic: 90,
    legendary: 120,
    unique: 175,
  },
  secondaryWeapon: {
    poor: 1,
    common: 2,
    uncommon: 21,
    rare: 28,
    epic: 42,
    legendary: 56,
    unique: 100,
  },
  head: {
    poor: 1,
    common: 1,
    uncommon: 12,
    rare: 16,
    epic: 24,
    legendary: 32,
    unique: 40,
  },
  hands: {
    poor: 1,
    common: 1,
    uncommon: 12,
    rare: 16,
    epic: 24,
    legendary: 32,
    unique: 40,
  },
  feet: {
    poor: 1,
    common: 1,
    uncommon: 12,
    rare: 16,
    epic: 24,
    legendary: 32,
    unique: 40,
  },
  chest: {
    poor: 1,
    common: 1,
    uncommon: 15,
    rare: 20,
    epic: 30,
    legendary: 40,
    unique: 50,
  },
  legs: {
    poor: 1,
    common: 1,
    uncommon: 15,
    rare: 20,
    epic: 30,
    legendary: 40,
    unique: 50,
  },
  back: {
    poor: 1,
    common: 1,
    uncommon: 15,
    rare: 20,
    epic: 30,
    legendary: 40,
    unique: 50,
  },
  necklace: {
    poor: 0,
    common: 0,
    uncommon: 9,
    rare: 12,
    epic: 18,
    legendary: 24,
    unique: 30,
  },
  ring: {
    poor: 0,
    common: 0,
    uncommon: 9,
    rare: 12,
    epic: 18,
    legendary: 24,
    unique: 30,
  },
  utility: {
    poor: 0,
    common: 0,
    uncommon: 6,
    rare: 8,
    epic: 12,
    legendary: 16,
    unique: 20,
  },
}

export const shortStateKeyMap: { [key: string]: string } = {
  head: 'h',
  necklace: 'n',
  hands: 'ha',
  chest: 'c',
  back: 'b',
  ring1: 'r1',
  legs: 'l',
  ring2: 'r2',
  feet: 'f',
  utility1: 'u1',
  utility2: 'u2',
  utility3: 'u3',
  utility4: 'u4',
  utility5: 'u5',
  utility6: 'u6',
}
